# Generated by Django 4.2.5 on 2023-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_produits_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='categorie',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
